//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMonacoForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestMonacoForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;monaco editor&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;style.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; data-name=&quot;vs/editor/editor.main&quot; href=&quot;node_modules/monaco-editor/min/vs/editor/editor.main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;container&quot;&gt;&lt;/div&gt;
        ///    &lt;script src=&quot;node_modules/monaco-editor/min/vs/loader.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;script&gt;
        ///        // Based on https://jsfiddle.net/developit/bwgkr6uq/ which just works but is based on un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;monaco editor&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;style.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; data-name=&quot;vs/editor/editor.main&quot; href=&quot;node_modules/monaco-editor/min/vs/editor/editor.main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;container&quot;&gt;&lt;/div&gt;
        ///    &lt;script src=&quot;node_modules/monaco-editor/min/vs/loader.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;script&gt;
        ///        // Based on https://jsfiddle.net/developit/bwgkr6uq/ which just works but is based on un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewer {
            get {
                return ResourceManager.GetString("viewer", resourceCulture);
            }
        }
    }
}
